name       : python-urllib3
version    : 1.26.7
release    : 9
source     :
    - https://files.pythonhosted.org/packages/source/u/urllib3/urllib3-1.26.7.tar.gz : 4987c65554f7a2dbf30c18fd48778ef124af6fab771a377103da0585e2336ece
license    : MIT
component  : programming.python
summary    : Python HTTP library with thread-safe connection pooling, file post, and more
description: |
    urllib3 is a powerful, sanity-friendly HTTP client for Python. Much of the Python ecosystem already uses urllib3 and you should too. urllib3 brings many critical features that are missing from the Python standard libraries.
builddeps  :
    - pkgconfig(python3)
    - python-dateutil
    - python-mock
    - python-nose
    - python-openssl
    - python-psutil
    - python-pysocks
    - python-pytest
    - python-tornado
    - python-trustme
rundeps    :
    - python-openssl
    - python-pysocks
setup      : |
    # Let's check these later
    rm -rf test/with_dummyserver/
    rm -rf test/appengine/
    rm -rf test/contrib/
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test pytest3 -k 'not test_connection'
