name       : python-urllib3
version    : 1.26.13
release    : 14
source     :
    - https://files.pythonhosted.org/packages/source/u/urllib3/urllib3-1.26.13.tar.gz : c083dd0dce68dbfbe1129d5271cb90f9447dea7d52097c6e0126120c521ddea8
homepage   : https://urllib3.readthedocs.io/
license    : MIT
component  : programming.python
summary    : Python HTTP library with thread-safe connection pooling, file post, and more
description: |
    urllib3 is a powerful, sanity-friendly HTTP client for Python. Much of the Python ecosystem already uses urllib3 and you should too. urllib3 brings many critical features that are missing from the Python standard libraries.
builddeps  :
    - python-dateutil # check
    - python-mock     # check
    - python-pysocks  # check
    - python-pytest   # check
    - python-tornado  # check
    - python-trustme  # check
rundeps    :
    - python-openssl
    - python-pysocks
setup      : |
    # Let's check these later
    rm -rf test/contrib/
    rm -rf test/test_retry*
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v --deselect test/with_dummyserver/test_socketlevel.py::TestSSL::test_ssl_read_timeout
