name       : python-urllib3
version    : 1.25.6
release    : 7
source     :
    - https://files.pythonhosted.org/packages/ff/44/29655168da441dff66de03952880c6e2d17b252836ff1aa4421fba556424/urllib3-1.25.6.tar.gz : 9a107b99a5393caf59c7aa3c1249c16e6879447533d0887f4336dde834c7be86
license    : MIT
component  : programming.python
summary    : Python HTTP library with thread-safe connection pooling, file post, and
    more
description: |
    urllib3 is a powerful, sanity-friendly HTTP client for Python. Much of the Python ecosystem already uses urllib3 and you should too. urllib3 brings many critical features that are missing from the Python standard libraries.
builddeps  :
    - pkgconfig(python3)
    - python-mock
    - python-nose
    - python-openssl
    - python-psutil
    - python-pysocks
    - python-pytest
    - python-setuptools
    - python-tornado
rundeps    :
    - python-openssl
    - python-pysocks
setup      : |
    # Let's check these later
    rm -rf test/with_dummyserver/
    rm -rf test/appengine/
    rm -rf test/contrib/
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test pytest -k 'not test_connection'
    %python3_test pytest -k 'not test_connection'
