name       : python-urllib3
version    : 1.26.11
release    : 12
source     :
    - https://files.pythonhosted.org/packages/source/u/urllib3/urllib3-1.26.11.tar.gz : ea6e8fb210b19d950fab93b60c9009226c63a28808bc8386e05301e25883ac0a
homepage   : https://urllib3.readthedocs.io/
license    : MIT
component  : programming.python
summary    : Python HTTP library with thread-safe connection pooling, file post, and more
description: |
    urllib3 is a powerful, sanity-friendly HTTP client for Python. Much of the Python ecosystem already uses urllib3 and you should too. urllib3 brings many critical features that are missing from the Python standard libraries.
builddeps  :
    - python-dateutil # check
    - python-mock     # check
    - python-pysocks  # check
    - python-pytest   # check
    - python-tornado  # check
    - python-trustme  # check
rundeps    :
    - python-openssl
    - python-pysocks
setup      : |
    # Let's check these later
    rm -rf test/appengine/
    rm -rf test/contrib/
    rm -rf test/test_retry*
    rm -rf test/with_dummyserver/
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -k 'not test_connection'
